server:
  port: 7923

spring:
  application:
    name: "nacos-in-action"
  profiles:
    active: dev

logging:
  level:
    root: info
  pattern:
    console: '%red(%d{yyyy-MM-dd HH:mm:ss.SSS}) %red([${spring.application.name}]) %green([%thread]) %highlight(%-5level) %boldMagenta(%logger) - %cyan(%msg%n)'